services:
  - type: web
    name: google-calendar-gmail-api
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn plugin_api:app --host 0.0.0.0 --port $PORT"
    plan: free 